version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass 111111 --appendonly yes
    environment:
      TZ: Asia/Shanghai
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data
  # bot业务
  pornbot:
    image: jwstar/pybot
    depends_on:
      - redis
    network_mode: host
    container_name: pybot
    restart: always
    volumes:
      - ./config:/config
      #保证本地时区正确 date查看时间
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      #windows配置环境变量需要重启电脑
      REDIS_HOST: 11.11.11.11
      REDIS_PORT: 16379
      REDIS_PASS: 111111
      API_ID: 1121122
      API_HASH: 2122222222212
      BOT_TOKEN: 311111:1221111111111
      GROUP_ID: 1111222 #定时任务首页爬取后要发送的群组id
      #选填
      CRON_HOUR_91: 6 #定时任务开始的小时（24小时制）
      CRON_MINUTE_91: 50 #定时任务开始的分（<60）

    # init处理僵尸进程，防止chrome进程没有被关闭
    init: true
    deploy:
      resources:
        limits:
          cpus: '0.80'